services:
  - type: web
    name: abbabal-api
    runtime: node
    repo: https://github.com/temesgen-982/abbabal
    region: oregon
    plan: free
    envVars:
      - key: NODE_VERSION
        value: '22'
      - key: PNPM_VERSION
        value: '10.15.0'
      - key: CORS_ORIGIN
        value: 'https://abbabal-api-web.vercel.app'
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
    buildCommand: pnpm install --frozen-lockfile --filter @abbabal/api... && pnpm build:api
    startCommand: pnpm --filter @abbabal/api start:prod
    healthCheckPath: /
